all: test_executable

test_executable: main.o vector.o
	g++ main.o vector.o -o test_executable

main.o: main.cpp vector.h
	g++ -c main.cpp

vector.o: vector.cpp vector.h
	g++ -c vector.cpp

clean:
	rm -f *.o test_executable *~ #*