all: test_executable

test_executable: main.o vector.o
	g++ main.o vector.o -o test_executable

main.o: main.cc vector.h
	g++ -c main.cc

vector.o: vector.cc vector.h
	g++ -c vector.cc

clean:
	rm -f *.o test_executable *~ #*
